In [1]:
import pandas as pd
import numpy as np

In [2]:
Dataset = pd.read_csv("\Quantium Intenship\Task 2\QVI_data.csv")

In [3]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264834 entries, 0 to 264833
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   LYLTY_CARD_NBR    264834 non-null  int64
 1   DATE              264834 non-null  object
 2   STORE_NBR         264834 non-null  int64
 3   TXN_ID            264834 non-null  int64
 4   PROD_NBR          264834 non-null  int64
 5   PROD_NAME         264834 non-null  object
 6   PROD_QTY          264834 non-null  int64
 7   TOT_SALES         264834 non-null  float64
 8   PACK_SIZE         264834 non-null  int64
 9   BRAND             264834 non-null  object
 10  LIFESTAGE         264834 non-null  object
 11  PREMIUM_CUSTOMER  264834 non-null  object
dtypes: float64(1), int64(6), object(5)
memory usage: 24.2+ MB

In [7]:
Dataset.head(9000)

,LYLTY_CARD_NBR,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND,LIFESTAGE,PREMIUM_CUSTOMER,YR
0,1000,2018-10-17,1,1,5,Natural Chip Compny SeaSalt175g,2,6.0,175,NATURAL,YOUNG SINGLES/COUPLES,Premium,201810
1,1002,2018-09-16,1,2,58,Red Rock Deli Chikn&Garlic Aioli 150g,1,2.7,150,RRD,YOUNG SINGLES/COUPLES,Mainstream,201809
2,1003,2019-03-07,1,3,52,Grain Waves Sour Cream&Chives 210G,1,3.6,210,GRNWVES,YOUNG FAMILIES,Budget,201903
3,1003,2019-03-08,1,4,106,Natural ChipCo Hony Soy Chckn175g,1,3.0,175,NATURAL,YOUNG FAMILIES,Budget,201903
4,1004,2018-11-02,1,5,96,WW Original Stacked Chips 160g,1,1.9,160,WOOLWORTHS,OLDER SINGLES/COUPLES,Mainstream,201811
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,10030,2019-03-15,10,9209,96,WW Original Stacked Chips 160g,2,3.8,160,WOOLWORTHS,OLDER SINGLES/COUPLES,Mainstream,201903
8996,10030,2019-05-27,10,9210,5,Natural Chip Compny SeaSalt175g,2,6.0,175,NATURAL,OLDER SINGLES/COUPLES,Mainstream,201905
8997,10031,2018-08-16,10,9212,12,Natural Chip Co Tmato Hrb&Spce 175g,4,12.0,175,NATURAL,OLDER FAMILIES,Budget,201808
8998,10031,2018-07-10,10,9211,47,Doritos Corn Chips Original 170g,2,8.8,170,DORITOS,OLDER FAMILIES,Budget,201807
8999,10031,2018-12-19,10,9213,110,WW Original Corn Chips 200g,2,3.8,200,WOOLWORTHS,OLDER FAMILIES,Budget,201812

In [5]:
Dataset["DATE"] = pd.to_datetime(Dataset["DATE"])
Dataset["YR"] = Dataset["DATE"].dt.strftime("%Y%m").astype("int")
Dataset["YR"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 264834 entries, 0 to 264833
Series name: YR
Non-Null Count   Dtype
--------------   -----
264834 non-null  int32
dtypes: int32(1)
memory usage: 1.0 MB

Compile Each Store's Monthly

1. Total Sales
2. Number of Customers
3. Average Transactions Per Customer
4. Average Chips Per Customer
5. Average Price per Unit

In [16]:
def monthly_store_metrics():
    store_yrmo_group = Dataset.groupby(["STORE_NBR" , "YR"])
    #Total sales
    total = store_yrmo_group["TOT_SALES"].sum()
    print(total)
    #Number of Customers
    cust_num = store_yrmo_group["LYLTY_CARD_NBR"].nunique()
    print(cust_num)
    
    
monthly_store_metrics()

STORE_NBR  YR
1          201807    206.9
           201808    176.1
           201809    278.8
           201810    188.1
           201811    192.6
                     ...
272        201902    395.5
           201903    442.3
           201904    445.1
           201905    314.6
           201906    312.1
Name: TOT_SALES, Length: 3169, dtype: float64
STORE_NBR  YR
1          201807    49
           201808    42
           201809    59
           201810    44
           201811    46
                     ..
272        201902    45
           201903    50
           201904    54
           201905    34
           201906    34
Name: LYLTY_CARD_NBR, Length: 3169, dtype: int64